// 24 provincias del Ecuador con sus principales ciudades/cantones.
export const ECUADOR: Record<string, string[]> = {
  Azuay: [
    "Cuenca",
    "Gualaceo",
    "Paute",
    "Sigsig",
    "Girón",
    "Santa Isabel",
    "Chordeleg",
    "Nabón",
    "Camilo Ponce Enríquez",
  ],
  Bolívar: ["Guaranda", "San Miguel", "Chillanes", "Echeandía", "Caluma", "Las Naves"],
  Cañar: ["Azogues", "La Troncal", "Cañar", "Biblián", "El Tambo", "Déleg", "Suscal"],
  Carchi: ["Tulcán", "Montúfar", "Bolívar", "Espejo", "Mira", "San Pedro de Huaca"],
  Chimborazo: [
    "Riobamba",
    "Alausí",
    "Guano",
    "Chambo",
    "Colta",
    "Cumandá",
    "Guamote",
    "Pallatanga",
    "Penipe",
    "Chunchi",
  ],
  Cotopaxi: ["Latacunga", "La Maná", "Pujilí", "Salcedo", "Saquisilí", "Sigchos", "Pangua"],
  "El Oro": [
    "Machala",
    "Pasaje",
    "Santa Rosa",
    "Huaquillas",
    "Arenillas",
    "El Guabo",
    "Piñas",
    "Zaruma",
    "Atahualpa",
    "Balsas",
    "Chilla",
    "Las Lajas",
    "Marcabelí",
    "Portovelo",
  ],
  Esmeraldas: [
    "Esmeraldas",
    "Atacames",
    "Quinindé",
    "Muisne",
    "Eloy Alfaro",
    "Río Verde",
    "San Lorenzo",
  ],
  Galápagos: ["Puerto Ayora", "Puerto Baquerizo Moreno", "Puerto Villamil"],
  Guayas: [
    "Guayaquil",
    "Daule",
    "Durán",
    "Samborondón",
    "Milagro",
    "Salinas",
    "Playas",
    "Naranjal",
    "Naranjito",
    "El Triunfo",
    "Yaguachi",
    "Balzar",
    "Salitre",
    "Colimes",
    "Pedro Carbo",
    "Santa Lucía",
    "Simón Bolívar",
    "Lomas de Sargentillo",
    "Nobol",
    "General Villamil",
    "Isidro Ayora",
    "Balao",
  ],
  Imbabura: ["Ibarra", "Otavalo", "Cotacachi", "Antonio Ante", "Pimampiro", "Urcuquí"],
  Loja: [
    "Loja",
    "Catamayo",
    "Cariamanga",
    "Macará",
    "Saraguro",
    "Celica",
    "Alamor",
    "Calvas",
    "Chaguarpamba",
    "Espíndola",
    "Gonzanamá",
    "Olmedo",
    "Paltas",
    "Pindal",
    "Puyango",
    "Quilanga",
    "Sozoranga",
    "Zapotillo",
  ],
  "Los Ríos": [
    "Babahoyo",
    "Quevedo",
    "Ventanas",
    "Vinces",
    "Buena Fe",
    "Valencia",
    "Mocache",
    "Montalvo",
    "Palenque",
    "Puebloviejo",
    "Quinsaloma",
    "Urdaneta",
    "Baba",
  ],
  Manabí: [
    "Portoviejo",
    "Manta",
    "Chone",
    "Jipijapa",
    "Bahía de Caráquez",
    "Pedernales",
    "El Carmen",
    "Calceta",
    "Montecristi",
    "Rocafuerte",
    "Santa Ana",
    "Sucre",
    "Tosagua",
    "24 de Mayo",
    "Flavio Alfaro",
    "Jama",
    "Junín",
    "Olmedo",
    "Paján",
    "Pichincha",
    "Puerto López",
    "San Vicente",
    "Jaramijó",
  ],
  "Morona Santiago": [
    "Macas",
    "Sucúa",
    "Gualaquiza",
    "Limón Indanza",
    "Palora",
    "Santiago",
    "Logroño",
    "Pablo Sexto",
    "Huamboya",
    "San Juan Bosco",
    "Taisha",
    "Tiwintza",
  ],
  Napo: ["Tena", "Archidona", "El Chaco", "Quijos", "Carlos Julio Arosemena Tola"],
  Orellana: ["Francisco de Orellana (Coca)", "La Joya de los Sachas", "Loreto", "Aguarico"],
  Pastaza: ["Puyo", "Mera", "Santa Clara", "Arajuno"],
  Pichincha: [
    "Quito",
    "Cayambe",
    "Mejía (Machachi)",
    "Pedro Moncayo (Tabacundo)",
    "Rumiñahui (Sangolquí)",
    "San Miguel de los Bancos",
    "Pedro Vicente Maldonado",
    "Puerto Quito",
  ],
  "Santa Elena": ["Santa Elena", "La Libertad", "Salinas"],
  "Santo Domingo de los Tsáchilas": ["Santo Domingo", "La Concordia"],
  Sucumbíos: [
    "Nueva Loja (Lago Agrio)",
    "Shushufindi",
    "Cascales",
    "Cuyabeno",
    "Gonzalo Pizarro",
    "Putumayo",
    "Sucumbíos",
  ],
  Tungurahua: [
    "Ambato",
    "Baños de Agua Santa",
    "Pelileo",
    "Píllaro",
    "Cevallos",
    "Mocha",
    "Patate",
    "Quero",
    "Tisaleo",
  ],
  "Zamora Chinchipe": [
    "Zamora",
    "Yantzaza",
    "Zumba",
    "El Pangui",
    "Centinela del Cóndor",
    "Chinchipe",
    "Nangaritza",
    "Palanda",
    "Paquisha",
    "Yacuambi",
  ],
};

export const PROVINCIAS = Object.keys(ECUADOR).sort();

export const TODAS_CIUDADES = Array.from(new Set(Object.values(ECUADOR).flat())).sort();
