/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as CategoriaIdRouteImport } from './routes/categoria.$id'
import { Route as AuthVerificarTelefonoRouteImport } from './routes/auth.verificar-telefono'
import { Route as AuthRecuperarRouteImport } from './routes/auth.recuperar'
import { Route as AuthNuevaContrasenaRouteImport } from './routes/auth.nueva-contrasena'
import { Route as AuthenticatedPublicarRouteImport } from './routes/_authenticated/publicar'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMisPublicacionesRouteImport } from './routes/_authenticated/mis-publicaciones'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPromocionarProductoIdRouteImport } from './routes/_authenticated/promocionar.$productoId'
import { Route as AuthenticatedEditarIdRouteImport } from './routes/_authenticated/editar.$id'
import { Route as AuthenticatedChatChatIdRouteImport } from './routes/_authenticated/chat.$chatId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaIdRoute = CategoriaIdRouteImport.update({
  id: '/categoria/$id',
  path: '/categoria/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerificarTelefonoRoute = AuthVerificarTelefonoRouteImport.update({
  id: '/verificar-telefono',
  path: '/verificar-telefono',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNuevaContrasenaRoute = AuthNuevaContrasenaRouteImport.update({
  id: '/nueva-contrasena',
  path: '/nueva-contrasena',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPublicarRoute = AuthenticatedPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisPublicacionesRoute =
  AuthenticatedMisPublicacionesRouteImport.update({
    id: '/mis-publicaciones',
    path: '/mis-publicaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromocionarProductoIdRoute =
  AuthenticatedPromocionarProductoIdRouteImport.update({
    id: '/promocionar/$productoId',
    path: '/promocionar/$productoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditarIdRoute = AuthenticatedEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatChatIdRoute = AuthenticatedChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/mis-publicaciones': typeof AuthenticatedMisPublicacionesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/publicar': typeof AuthenticatedPublicarRoute
  '/auth/nueva-contrasena': typeof AuthNuevaContrasenaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/verificar-telefono': typeof AuthVerificarTelefonoRoute
  '/categoria/$id': typeof CategoriaIdRoute
  '/producto/$id': typeof ProductoIdRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
  '/promocionar/$productoId': typeof AuthenticatedPromocionarProductoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/mis-publicaciones': typeof AuthenticatedMisPublicacionesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/publicar': typeof AuthenticatedPublicarRoute
  '/auth/nueva-contrasena': typeof AuthNuevaContrasenaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/verificar-telefono': typeof AuthVerificarTelefonoRoute
  '/categoria/$id': typeof CategoriaIdRoute
  '/producto/$id': typeof ProductoIdRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
  '/promocionar/$productoId': typeof AuthenticatedPromocionarProductoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/mis-publicaciones': typeof AuthenticatedMisPublicacionesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/publicar': typeof AuthenticatedPublicarRoute
  '/auth/nueva-contrasena': typeof AuthNuevaContrasenaRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/verificar-telefono': typeof AuthVerificarTelefonoRoute
  '/categoria/$id': typeof CategoriaIdRoute
  '/producto/$id': typeof ProductoIdRoute
  '/_authenticated/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/_authenticated/editar/$id': typeof AuthenticatedEditarIdRoute
  '/_authenticated/promocionar/$productoId': typeof AuthenticatedPromocionarProductoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/chats'
    | '/mis-publicaciones'
    | '/perfil'
    | '/publicar'
    | '/auth/nueva-contrasena'
    | '/auth/recuperar'
    | '/auth/verificar-telefono'
    | '/categoria/$id'
    | '/producto/$id'
    | '/chat/$chatId'
    | '/editar/$id'
    | '/promocionar/$productoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/chats'
    | '/mis-publicaciones'
    | '/perfil'
    | '/publicar'
    | '/auth/nueva-contrasena'
    | '/auth/recuperar'
    | '/auth/verificar-telefono'
    | '/categoria/$id'
    | '/producto/$id'
    | '/chat/$chatId'
    | '/editar/$id'
    | '/promocionar/$productoId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/chats'
    | '/_authenticated/mis-publicaciones'
    | '/_authenticated/perfil'
    | '/_authenticated/publicar'
    | '/auth/nueva-contrasena'
    | '/auth/recuperar'
    | '/auth/verificar-telefono'
    | '/categoria/$id'
    | '/producto/$id'
    | '/_authenticated/chat/$chatId'
    | '/_authenticated/editar/$id'
    | '/_authenticated/promocionar/$productoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CategoriaIdRoute: typeof CategoriaIdRoute
  ProductoIdRoute: typeof ProductoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$id': {
      id: '/categoria/$id'
      path: '/categoria/$id'
      fullPath: '/categoria/$id'
      preLoaderRoute: typeof CategoriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verificar-telefono': {
      id: '/auth/verificar-telefono'
      path: '/verificar-telefono'
      fullPath: '/auth/verificar-telefono'
      preLoaderRoute: typeof AuthVerificarTelefonoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/nueva-contrasena': {
      id: '/auth/nueva-contrasena'
      path: '/nueva-contrasena'
      fullPath: '/auth/nueva-contrasena'
      preLoaderRoute: typeof AuthNuevaContrasenaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/publicar': {
      id: '/_authenticated/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof AuthenticatedPublicarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-publicaciones': {
      id: '/_authenticated/mis-publicaciones'
      path: '/mis-publicaciones'
      fullPath: '/mis-publicaciones'
      preLoaderRoute: typeof AuthenticatedMisPublicacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promocionar/$productoId': {
      id: '/_authenticated/promocionar/$productoId'
      path: '/promocionar/$productoId'
      fullPath: '/promocionar/$productoId'
      preLoaderRoute: typeof AuthenticatedPromocionarProductoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editar/$id': {
      id: '/_authenticated/editar/$id'
      path: '/editar/$id'
      fullPath: '/editar/$id'
      preLoaderRoute: typeof AuthenticatedEditarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$chatId': {
      id: '/_authenticated/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedChatChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedMisPublicacionesRoute: typeof AuthenticatedMisPublicacionesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPublicarRoute: typeof AuthenticatedPublicarRoute
  AuthenticatedChatChatIdRoute: typeof AuthenticatedChatChatIdRoute
  AuthenticatedEditarIdRoute: typeof AuthenticatedEditarIdRoute
  AuthenticatedPromocionarProductoIdRoute: typeof AuthenticatedPromocionarProductoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedMisPublicacionesRoute: AuthenticatedMisPublicacionesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPublicarRoute: AuthenticatedPublicarRoute,
  AuthenticatedChatChatIdRoute: AuthenticatedChatChatIdRoute,
  AuthenticatedEditarIdRoute: AuthenticatedEditarIdRoute,
  AuthenticatedPromocionarProductoIdRoute:
    AuthenticatedPromocionarProductoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthNuevaContrasenaRoute: typeof AuthNuevaContrasenaRoute
  AuthRecuperarRoute: typeof AuthRecuperarRoute
  AuthVerificarTelefonoRoute: typeof AuthVerificarTelefonoRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNuevaContrasenaRoute: AuthNuevaContrasenaRoute,
  AuthRecuperarRoute: AuthRecuperarRoute,
  AuthVerificarTelefonoRoute: AuthVerificarTelefonoRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CategoriaIdRoute: CategoriaIdRoute,
  ProductoIdRoute: ProductoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
