// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createUnavailableSupabaseClient() {
  const unavailableMessage =
    "Supabase no está configurado. Define VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY para habilitar el backend.";

  const makeErrorResult = <T>(data: T | null = null) => ({ data, error: { message: unavailableMessage } });

  const createQueryBuilder = () => {
    const base: Record<string, unknown> = {
      data: null,
      error: { message: unavailableMessage },
    };

    const builder = Object.assign(Promise.resolve(base), {
      select() {
        return this;
      },
      order() {
        return this;
      },
      eq() {
        return this;
      },
      or() {
        return this;
      },
      ne() {
        return this;
      },
      neq() {
        return this;
      },
      gt() {
        return this;
      },
      gte() {
        return this;
      },
      lt() {
        return this;
      },
      lte() {
        return this;
      },
      in() {
        return this;
      },
      ilike() {
        return this;
      },
      range() {
        return this;
      },
      limit() {
        return this;
      },
      single() {
        return Promise.resolve({ data: null, error: { message: unavailableMessage } });
      },
      maybeSingle() {
        return Promise.resolve({ data: null, error: { message: unavailableMessage } });
      },
      insert() {
        return Promise.resolve({ data: null, error: { message: unavailableMessage } });
      },
      update() {
        return Promise.resolve({ data: null, error: { message: unavailableMessage } });
      },
      upsert() {
        return Promise.resolve({ data: null, error: { message: unavailableMessage } });
      },
      delete() {
        return Promise.resolve({ data: null, error: { message: unavailableMessage } });
      },
    });

    return builder;
  };

  if (typeof window !== "undefined") {
    try {
      localStorage.setItem("supabase_down", "1");
    } catch {
      // Ignore storage errors in restricted environments.
    }
  }

  const authMethods = {
    onAuthStateChange() {
      return {
        data: {
          subscription: {
            unsubscribe() {},
          },
        },
      };
    },
    getSession() {
      return Promise.resolve({ data: { session: null }, error: null });
    },
    getUser() {
      return Promise.resolve({ data: { user: null }, error: null });
    },
    getClaims() {
      return Promise.resolve({ data: { claims: null }, error: null });
    },
    signOut() {
      return Promise.resolve({ error: null });
    },
    signInWithOAuth() {
      return Promise.resolve({ data: { provider: null }, error: { message: unavailableMessage } });
    },
    signInWithPassword() {
      return Promise.resolve({ data: { session: null, user: null }, error: { message: unavailableMessage } });
    },
    signInWithOtp() {
      return Promise.resolve({ data: { session: null, user: null }, error: { message: unavailableMessage } });
    },
    signUp() {
      return Promise.resolve({ data: { session: null, user: null }, error: { message: unavailableMessage } });
    },
    resetPasswordForEmail() {
      return Promise.resolve({ data: null, error: { message: unavailableMessage } });
    },
    verifyOtp() {
      return Promise.resolve({ data: { session: null, user: null }, error: { message: unavailableMessage } });
    },
    updateUser() {
      return Promise.resolve({ data: { user: null }, error: null });
    },
  };

  const storageMethods = {
    from() {
      return {
        upload() {
          return Promise.resolve({ data: null, error: { message: unavailableMessage } });
        },
        update() {
          return Promise.resolve({ data: null, error: { message: unavailableMessage } });
        },
        remove() {
          return Promise.resolve({ data: null, error: { message: unavailableMessage } });
        },
        list() {
          return Promise.resolve({ data: [], error: { message: unavailableMessage } });
        },
        download() {
          return Promise.resolve({ data: null, error: { message: unavailableMessage } });
        },
        getPublicUrl() {
          return { data: { publicUrl: "" }, error: { message: unavailableMessage } };
        },
        createSignedUrl() {
          return Promise.resolve({ data: { signedUrl: "", path: "" }, error: { message: unavailableMessage } });
        },
        createSignedUrls(paths: string[]) {
          return Promise.resolve({
            data: paths.map((path) => ({ signedUrl: "", path })),
            error: { message: unavailableMessage },
          });
        },
      };
    },
  };

  return {
    auth: authMethods,
    storage: storageMethods,
    rpc() {
      return Promise.resolve({ data: null, error: { message: unavailableMessage } });
    },
    from() {
      return createQueryBuilder();
    },
    channel() {
      return {
        subscribe() {
          return {
            unsubscribe() {},
          };
        },
      };
    },
    removeChannel() {},
    getSession() {
      return Promise.resolve({ data: { session: null }, error: null });
    },
    signOut() {
      return Promise.resolve({ error: null });
    },
    __unavailable: true,
  };
}

function createSupabaseClient() {
  // Vercel exposes these as browser variables, so prefer them directly.
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ?? "";
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
    import.meta.env.VITE_SUPABASE_ANON_KEY ??
    "";

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY"] : []),
    ];
    const message = `Missing Supabase browser variable(s): ${missing.join(", ")}. Add them in Vercel project settings.`;
    console.warn(`[Supabase] ${message}`);
    return createUnavailableSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
